name: label-action-test
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Just a test!